### PR TITLE
Home page init

### PR DESCRIPTION
**Pull request by AVS18**
this is another updated version of webpage. kindly check and reply sir

### CODE REVIEW

**Comment by abhieshekumar** [comment]
Closing this one, push changes corresponding to #2 as there are pending reviews in that one

**Comment by AVS18** [comment]
I didn't understand sir

**Comment by daemonsloth** [comment]
@AVS18 see this, https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo

**Comment by AVS18** [comment]
ok

**Pull request closed without merging**
